version: '3'
services:
  movies:
  image: manish27092007/paymovies:latest
  ports:
    - "81:80"
  deploy:
    replicas: 3
  train:
  image: manish27092007/paytrain:latest
  ports:
    - "82:80"
  deploy:
    replicas: 3
  dht:
  image: manish27092007/paydht:latest
  ports:
    - "83:80"
  deploy:
    replicas: 3
  recharge:
  image: manish27092007/payrecharge:latest
  ports:
    - "84:80"
  deploy:
    replicas: 3
